# Generated by Django 3.2.8 on 2023-06-07 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Libreria', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='description',
            new_name='descripción',
        ),
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(null=True, upload_to='Imagenes/', verbose_name='Imaneges/'),
        ),
        migrations.AddField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=100, null=True, verbose_name='Titulo'),
        ),
    ]
